### PR TITLE
Add Glance, Cinder and Heat support for OSP13

### PR DESCRIPTION
**Pull request by hmakkapati**

### CODE REVIEW

**Comment by hughsaunders** [comment]
recheck_all

**Comment by tonytan4ever** [comment]
`07:56:38 TASK [Install cinder api checks] ***********************************************
07:56:38 Thursday 22 November 2018  13:56:38 +0000 (0:00:00.200)       0:07:52.525 ***** 
07:56:38 fatal: [aio1_cinder_api_container-8712c6a1 -> 172.29.236.100]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'deploy_osp' is undefined"}`

Maybe using 

>  {% if deploy_osp | default(False) %}

**Comment by hmakkapati** [comment]
recheck_bionic_mnaio_3ctlr_2comp_3ceph_osp_13_deploy

**Comment by tonytan4ever** [comment]
recheck_xenial_queens_deploy

**Pull request merged**
