### PR TITLE
FLEEK-42 Add support for Open Manage 9.1.0 for Dell 14G

### PR DESCRIPTION
**Pull request by antonym**
Adds support for 9.1.0 of Open Manage for Dell 14G.

http://linux.dell.com/repo/community/openmanage/
http://topics-cdn.dell.com/pdf/dell-openmanage-software-9.1_support-matrix_en-us.pdf

### CODE REVIEW

**Comment by npawelek** [comment]
recheck_cit_trusty_newton_deploy
recheck_cit_xenial_ceph_deploy
recheck_cit_xenial_newton_deploy
recheck_cit_xenial_pike_deploy

**Comment by antonym** [comment]
recheck_all

**Comment by antonym** [comment]
Release note added.

**Comment by tonytan4ever** [comment]
recheck_cit_trusty_newton_deploy
recheck_cit_xenial_newton_deploy
recheck_cit_xenial_pike_deploy

**Comment by antonym** [comment]
recheck_all

**Comment by tonytan4ever** [comment]
recheck_cit_trusty_liberty_deploy

**Pull request merged**
