### PR TITLE
K8S-1361 rpc-maas doesn't install designate tests on RPC-R

### PR DESCRIPTION
**Pull request by xgerman**
Refactors Designate checks to work with RPC-R

### CODE REVIEW

**Comment by tonytan4ever** [comment]
recheck_trusty_liberty_deploy
recheck_xenial_pike_deploy

**Comment by tonytan4ever** [comment]
recheck_xenial_pike_deploy

**Comment by tonytan4ever** [comment]
recheck_ trusty_liberty_deploy
recheck_trusty_mitaka_deploy

**Comment by tonytan4ever** [comment]
recheck_trusty_liberty_deploy

**Comment by xgerman** [comment]
Couldn't download galera client - rechecking

recheck_trusty_liberty_deploy

**Comment by mattt416** [comment]
recheck_trusty_liberty_deploy

**Comment by tonytan4ever** [comment]
recheck_trusty_liberty_deploy

**Pull request merged**
