### PR TITLE
Enable http authentication for influxdb and telegraf

### PR DESCRIPTION
**Pull request by npawelek**
Initial commit to enabling authentication between influxdb and telgraf. Requires some additional testing/validation.

### CODE REVIEW

**Comment by npawelek** [comment]
recheck_cit_xenial_ceph_deploy

**Comment by andymcc** [comment]
recheck_cit_xenial_ceph_deploy

This failed before rpc-ceph came into it, repo failures upstream:
17:19:16 TASK [willshersystems.sshd : Installed] ****************************************
17:19:23 
failed: [prmmxcd-83-7f4] (item=[u'openssh-server', u'openssh-sftp-server']) => {"cmd": "apt-get update", "failed": true, "item": ["openssh-server", "openssh-sftp-server"], "msg": "E: Failed to fetch http://rackspace.clouds.archive.ubuntu.com/ubuntu/dists/xenial-updates/universe/source/Sources.xz  Hash Sum mismatch\nE: Failed to fetch

**Comment by tonytan4ever** [comment]
recheck_cit_xenial_ceph_deploy
recheck_cit_trusty_mitaka_deploy

**Comment by tonytan4ever** [comment]
recheck_cit_xenial_ceph_deploy

**Comment by andymcc** [comment]
recheck_cit_xenial_ceph_deploy

I was unable to recreate this issue with the lxc_container build out.

**Comment by andymcc** [comment]
The Ceph job doesn't read the passwords/vars files from /opt/openstack_deploy/*.yml - this seems to be a valid failure.

I've put a PR into the rpc-ceph repo that should help fix this: https://github.com/rcbops/rpc-ceph/pull/133

**Comment by andymcc** [comment]
recheck_cit_xenial_ceph_deploy

**Comment by npawelek** [comment]
recheck_cit_xenial_ceph_deploy

**Comment by tonytan4ever** [comment]
recheck_cit_xenial_ceph_deploy

**Comment by tonytan4ever** [comment]
recheck_xenial_ceph_deploy

**Pull request closed without merging**
