### PR TITLE
Drop keyring file on osds

### PR DESCRIPTION
**Pull request by npawelek**
Add task to drop the ceph keyring on the osds nodes as it's needed by the ceph_osd_stats check.

### CODE REVIEW

**Comment by cloudnull** [comment]
This looks good however I think we need to add the playbook to capture this key here too. Maybe make it an include playbook? This bit could be an included playbook in both the osd and mons playbooks: https://github.com/npawelek/rpc-maas/blob/cb768bd769f92f60fb116e64b950e037437e08ba/playbooks/maas-ceph-mon.yml#L28-L38 making it so neither playbook is dependent on one

**Comment by cloudnull** [comment]
I added to your commit.

**Comment by npawelek** [comment]
It looks like this is properly dropping the raxmon keyring to all ceph nodes, however, the restart handler isn't functioning properly. It looks like both mons hosts are restarting and only the first of the osds.

**Comment by npawelek** [comment]
I reverted these changes and I'm still seeing the issue. I believe the restart handler problem is a result of the current standalone inventory being used on this AIO.  We should be safe to merge these changes.

**Comment by npawelek** [comment]
recheck_cit_rpc-maas_master_trusty_liberty
recheck_cit_rpc-maas_master_trusty_mitaka

**Pull request merged**
