### PR TITLE
INTAKERPC-141:  Add neutron ovs agent check.

### PR DESCRIPTION
**Pull request by tonytan4ever**

### CODE REVIEW

**Comment by npawelek** [comment]
@tonytan4ever Looks like there was a discussion in the intake to setup OVS for testing this functionality. I think the only thing that stands out is the methodology for deploying it. Per the initial commit, I don't see an inclusion of the `maas-openstack-neutron.yml` playbook to determine whether `ovs` or `linuxbridge` monitoring is deployed on an environment.

**Comment by tonytan4ever** [comment]
@npawelek:  I have committed new changes to address the concern you have. We can proceed to test now.

**Comment by npawelek** [comment]
@tonytan4ever Thanks. In the context of deploying playbooks on an environment with OVS, I believe the linuxbridge agent check will also deploy as that group still exists. Correct me if I'm wrong, I think we'd only want to do one or the other?

**Comment by cloudnull** [comment]
@npawelek you are correct. We'd only want to deploy an agent verification check for a system in service. So the playbooks should be able to detect the network agent in service and deploy a compatible monitor.

**Comment by tonytan4ever** [comment]
@npawelek:  I added condition for installing linuxbridge agent check, and ovs agent check condition in place. Lmk if there is anything else missing.

**Comment by npawelek** [comment]
recheck_cit_trusty_mitaka

**Comment by npawelek** [comment]
@tonytan4ever looks like this is also failing pep8

**Comment by npawelek** [comment]
recheck_cit_trusty_mitaka

**Comment by npawelek** [comment]
recheck_cit_trusty_liberty

**Comment by tonytan4ever** [comment]
recheck_xenial_master

**Comment by tonytan4ever** [comment]
recheck_cit_xenial_master

**Pull request merged**
