### PR TITLE
Galera Check not working if wsrep_local_state is != 4

### PR DESCRIPTION
**Pull request by BjoernT**
This pull requests adds another check if the local state is not Synced.

### CODE REVIEW

**Comment by claco** [comment]
Shouldn't we really make that an else case after https://github.com/rcbops/rpc-maas/pull/175/files#diff-f5fd9e75668ee31c9857a3e2e2b7388fL111 so we catch all unknown or unplanned states?

**Comment by BjoernT** [comment]
@claco  Yeah I was thinking the same. Let me lookup all status states if 4 is the only good one.

**Comment by BjoernT** [comment]
According http://galeracluster.com/documentation-webpages/nodestates.html#node-state-changes, 4 is the only synced state and 5 indicated it goes into a donor state which might be still ok

**Comment by mancdaz** [comment]
@BjoernT @claco since all rpc-maas code for master/kilo has been migrated to rpc-extras, could this PR please be retargeted at rpc-extras.  I'm won't migrate it myself as it appears there is still discussion around the actual implementation.

**Pull request closed without merging**
