### PR TITLE
Remove maas_plugin_dir and fix associated templates

### PR DESCRIPTION
**Pull request by npawelek**
Update container_storage_checks.yaml.j2 to remove venv wrapper in stable/kilo.

Fixes: #264

### CODE REVIEW

**Comment by BjoernT** [comment]
👍  It seems to me, that maas_plugin_dir is now obsolete with this change, so let's remove it

**Comment by npawelek** [comment]
Hrm, good catch. Looks like the only other place `maas_plugin_dir` is still used is within hp-check.yaml.j2[1]. Let me update that template as it's broken too, then I'll remove the `maas_plugin_dir` variable entirely.

[1] https://github.com/rcbops/rpc-maas/blob/stable/kilo/templates/hp-check.yaml.j2#L9-L10

**Comment by npawelek** [comment]
Updated. How's this look @BjoernT?

**Comment by cloudnull** [comment]
@npawelek @BjoernT is the removal of this being done as a kilo specific change? Something that was accidentally backported?

**Comment by npawelek** [comment]
@cloudnull I'm not sure why the stable/kilo and stable/liberty branches have references to venv's in the plugin templates. They fail upon install, as the venv wrapper wasn't included until Mitaka. I'll need to replicate these same changes to stable/liberty.

**Comment by cloudnull** [comment]
sounds good to me !

**Pull request merged**
