### PR TITLE
Remove the elasticsearch maas check

### PR DESCRIPTION
**Pull request by cloudnull**
The elasticsearch maas check is not doing a whole lot and is more noise
than value. This is on top of the fact that the elasticsearch checks are
not made for a deployment where elasticsearch/logstash are deployed in a
high performance cluster.

This change follows on with the removal of the filebeat check.

Signed-off-by: Kevin Carter <kevin.carter@rackspace.com>
Issue: [FLEEK-126](https://rpc-openstack.atlassian.net/browse/FLEEK-126)

### CODE REVIEW

**Comment by cloudnull** [comment]
@npawelek and @tonytan4ever it looks like this is failing for some other, non-related, reason. Can you guys have a look and see why? I'm happy to iterate on this patch to resolve the issue however I'm not sure where to get started with this error.

**Comment by tonytan4ever** [comment]
@cloudnull :  See it here:
https://github.com/rcbops/rpc-maas/pull/527#discussion_r197261653

Seems like this change removed _maas_excluded_checks_regex_  some how...

**Comment by cloudnull** [comment]
recheck_cit_xenial_pike_deploy

**Comment by cloudnull** [comment]
recheck_xenial_pike_deploy

**Comment by cloudnull** [comment]
recheck_xenial_newton_deploy

**Comment by cloudnull** [comment]
recheck_trusty_newton_deploy

**Comment by cloudnull** [comment]
@tonytan4ever @npawelek mind have a look at why newton / pike are un-happy here? I cant seem to see anything in this change that would be causing the noted failures.

**Pull request merged**
