### PR TITLE
Fixing ansible linting errors

### PR DESCRIPTION
**Pull request by BjoernT**
Addressing ansible-lint errors within maas-tigkstack and verify

### CODE REVIEW

**Comment by BjoernT** [comment]
recheck_cit_trusty_kilo

**Comment by BjoernT** [comment]
@tonytan4ever @briancurtin Could you please check why so many CIT gating jobs are failing with unrelated issues to this PR

**Comment by tonytan4ever** [comment]
recheck_cit_trusty_liberty

**Comment by tonytan4ever** [comment]
recheck_cit_trusty_kilo

**Comment by tonytan4ever** [comment]
recheck_cit_xenial_pike

**Comment by tonytan4ever** [comment]
recheck_cit_xenial_newton
recheck_cit_xenial_ceph

**Comment by tonytan4ever** [comment]
@BjoernT:  I looked at one failure looks like there's something timed out: 

```
Step Complete: Destroy Slave
[Pipeline] echo
Caught exception on long-running-slave-22-32e7: hudson.AbortException: script returned exit code 1
```

**Comment by tonytan4ever** [comment]
recheck_cit_xenial_ceph

**Comment by tonytan4ever** [comment]
recheck_cit_xenial_ceph

**Comment by tonytan4ever** [comment]
recheck_cit_xenial_newton

**Comment by tonytan4ever** [comment]
recheck_cit_trusty_liberty
recheck_cit_xenial_newton
recheck_cit_xenial_ceph

**Comment by tonytan4ever** [comment]
recheck_cit_trusty_liberty
recheck_cit_xenial_ceph

**Pull request merged**
