### PR TITLE
TURTLES-673: Phase 1 maas_rally improvements

### PR DESCRIPTION
**Pull request by cfarquhar**
This task tracks the following improvements:

```
- Add logging
- Add resiliency to transitory environmental problems
  - Automatically recover from stale locks
  - Automatically clean up stale resources
```

Some prerequisite refactoring for the items above:

```
- Some information from ansible runtime is required during plugin runtime and was moved to the maas_rally.yml plugin config file:
  - Scenario project, username, and password
  - Alert thresholds
  - Primary resources created by each scenario
- Added a quota factor that each scenario project's quotas are multiplied by.  This allows a scenario to call for cleanup without waiting for cleanup to finish.
- Add alarms for:
  - Too many consecutive intervals requiring stale resource cleanup
  - Too many consecutive intervals waiting for immature locks
```

### CODE REVIEW

**Comment by cfarquhar** [comment]
recheck_cit_container_ansible-lint_tox-test

**Comment by tonytan4ever** [comment]
recheck_cit_container_ansible-lint_tox-test

**Comment by cfarquhar** [comment]
Rebased now that gating is unblocked

**Comment by cfarquhar** [comment]
recheck_cit_trusty_liberty_deploy

**Pull request merged**
