### PR TITLE
Use the new HP ssacli over hpssacli

### PR DESCRIPTION
**Pull request by BjoernT**
HP has begun replacing the hpssacli package with ssacli.
The arguments and output format are still the same,
requring minimal effort to make this change.
The HP MCP version is managed as part of the openstack-ops module
and is now frozen to version 10.6 to better synchronize these changes

Closes-Bug: RO-3090

### CODE REVIEW

**Comment by BjoernT** [comment]
I will redo this patch to account for a transition phase where either one or both of the binaries are installed

**Comment by npawelek** [comment]
@BjoernT It does appear that travis-ci is failing lint

**Comment by BjoernT** [comment]
@npawelek I know, it fails in the tigk stuff, so unrelated. I'm looking at these in a different PR as this one is just fine

**Comment by npawelek** [comment]
recheck_cit_trusty_mitaka

**Pull request merged**
