### PR TITLE
Enabling osp-13 maas gate

### PR DESCRIPTION
**Pull request by hmakkapati**

### CODE REVIEW

**Comment by hmakkapati** [comment]
recheck_all

**Comment by tonytan4ever** [comment]
recheck_bionic_mnaio_3ctlr_2comp_3ceph_osp_13_deploy

**Comment by tonytan4ever** [comment]
recheck_bionic_mnaio_3ctlr_2comp_3ceph_osp_13_deploy

**Comment by tonytan4ever** [comment]
recheck_bionic_mnaio_3ctlr_2comp_3ceph_osp_13_deploy

**Comment by hughsaunders** [comment]
recheck_all

**Comment by hughsaunders** [comment]
recheck_all

**Comment by tonytan4ever** [comment]
recheck_bionic_mnaio_3ctlr_2comp_3ceph_osp_13_deploy
recheck_trusty_liberty_deploy
recheck_trusty_mitaka_deploy 
recheck_xenial_ceph_deploy

**Comment by tonytan4ever** [comment]
recheck_xenial_ceph_deploy
recheck_trusty_newton_deploy 
recheck_xenial_newton_deploy
recheck_xenial_pike_deploy
recheck_xenial_queens_deploy

**Comment by hughsaunders** [comment]
recheck_container_bandit_tox-test recheck trusty_newton_deploy recheck xenial_pike_deploy recheck_xenial_rocky_deploy

**Comment by hughsaunders** [comment]
recheck_trusty_newton_deploy recheck_xenial_pike_deploy

**Comment by tonytan4ever** [comment]
recheck_bionic_mnaio_3ctlr_2comp_3ceph_osp_13_deploy

**Comment by hughsaunders** [comment]
recheck_bionic_mnaio_3ctlr_2comp_3ceph_osp_13_deploy

**Comment by tonytan4ever** [comment]
recheck_xenial_queens_deploy

**Comment by tonytan4ever** [comment]
recheck_xenial_queens_deploy

**Comment by tonytan4ever** [comment]
recheck_bionic_mnaio_3ctlr_2comp_3ceph_osp_13_deploy

**Comment by tonytan4ever** [comment]
recheck_bionic_mnaio_3ctlr_2comp_3ceph_osp_13_deploy

**Pull request merged**
