### PR TITLE
Add multipath check

### PR DESCRIPTION
**Pull request by cloudnull**
This change adds a multipath check which will now look for the multipath
process and if the process its found, and there are active connections,
a process check will be deployed. This check will alert if the process
dies or ever becomes unresponsive.

Signed-off-by: cloudnull <kevin@cloudnull.com>

### CODE REVIEW

**Comment by cloudnull** [comment]
recheck_xenial_rocky_deploy

**Comment by cloudnull** [comment]
recheck_xenial_queens_deploy

**Comment by cloudnull** [comment]
recheck_xenial_queens_deploy

**Comment by cloudnull** [comment]
recheck_xenial_pike_deploy

**Comment by cloudnull** [comment]
recheck_xenial_pike_deploy

**Comment by cloudnull** [comment]
recheck_trusty_newton_deploy

**Comment by cloudnull** [comment]
recheck_bionic_rocky_deploy

**Comment by cloudnull** [comment]
recheck_bionic_rocky_deploy

**Comment by npawelek** [comment]
recheck_xenial_pike_deploy

**Pull request merged**
