### PR TITLE
Add horizon/keystone checks support for rpcr osp13

### PR DESCRIPTION
**Pull request by tonytan4ever**

### CODE REVIEW

**Comment by tonytan4ever** [comment]
recheck_al

**Comment by tonytan4ever** [comment]
recheck_all

**Comment by tonytan4ever** [comment]
recheck_trusty_liberty_deploy

**Comment by tonytan4ever** [comment]
recheck_trusty_mitaka_deploy

**Comment by tonytan4ever** [comment]
recheck_xenial_queens_deploy

**Comment by hmakkapati** [comment]
Is the Horizon playbook not supposed to get the `environment` directive?

**Comment by tonytan4ever** [comment]
recheck_xenial_queens_deploy

**Comment by tonytan4ever** [comment]
recheck_xenial_queens_deploy

**Pull request merged**
