### PR TITLE
[WIP] Fix logic for CDM alarm regex

### PR DESCRIPTION
**Pull request by npawelek**
Fix issue where `maas_excluded_alarms` wasn't disabling properly when defined.

### CODE REVIEW

**Comment by npawelek** [comment]
recheck_trusty_liberty_deploy
recheck_trusty_mitaka_deploy
recheck_trusty_newton_deploy

**Comment by npawelek** [comment]
recheck_trusty_liberty_deploy
recheck_trusty_mitaka_deploy
recheck_trusty_newton_deploy

**Comment by mattt416** [comment]
recheck_trusty_liberty_deploy
recheck_trusty_mitaka_deploy
recheck_trusty_newton_deploy

**Comment by tonytan4ever** [comment]
echeck_xenial_ceph_deploy
recheck_xenial_newton_deploy
recheck_xenial_pike_deploy

**Comment by tonytan4ever** [comment]
recheck_xenial_ceph_deploy

**Comment by tonytan4ever** [comment]
recheck_cit_xenial_ceph_deploy
recheck_cit_xenial_pike_deploy
recheck_cit_trusty_liberty_deploy 
recheck_cit_trusty_mitaka_deploy

**Comment by tonytan4ever** [comment]
recheck_cit_trusty_liberty_deploy

**Comment by npawelek** [comment]
No longer an issue. Closing.

**Pull request closed without merging**
