### PR TITLE
Addrgwmon

### PR DESCRIPTION
**Pull request by letterj**
This is a rework of the ceph rgw status alert and plugin based on review comments.   
From original pull request
Addition of rgw montioring for ceph Rados Gateway.

This adds general monitoring for nodes in the rgws group.
Adds a local check that hits the rgw endpoint ( http://localhost:/) and returns:
0 = Failure to Connect or Other failure (Critical)
1 = Status Code > 299 (WARNING)
2 = Status Code >= 200 < 299 . (OK)

### CODE REVIEW

**Comment by andymcc** [comment]
recheck_cit_trusty_liberty

**Comment by letterj** [comment]
Per request by Nathan:

./run_plugin_in_venv.sh /usr/lib/rackspace-monitoring-agent/plugins/ceph_monitoring.py --name client.raxmon --keyring /etc/ceph/ceph.client.raxmon.keyring rgw --rgw_port 8080 --rgw_host 10.1.1.106 

status okay
metric rgw_up uint32 2

**Comment by cloudnull** [comment]
While this PR seems fine, I still see no tests for ceph. @andymcc / @letterj / @npawelek are we OK just verifying that this isn't creating any regressions?

**Comment by letterj** [comment]
This rpc-maas branch was run against the AIO created in this repo .  https://github.com/rcbops/rpc-ceph, which includes a test to make sure the Rados gateway was set up properly.   tests/test-rgw.yml

Is there something that tests the alerts and checks?

**Comment by cloudnull** [comment]
It's great that its being tested by hand but until we've got an automated test **here** we've effectively no tests with regard to ceph and our rpc-maas integration. Meaning any commit at any time could break our ceph monitoring solution and we've never know until its tested again by hand.

**Comment by letterj** [comment]
Is there currently tests for the existing ceph monitoring (mons, osds)?  If so can you send me a link.

This jenkins job is deploying the current rpc-ceph AIO which also installs rpc-maas.   https://rpc.jenkins.cit.rackspace.net/job/RPC-IRR_rpc-ceph-master-xenial-master/

**Comment by andymcc** [comment]
https://github.com/rcbops/rpc-ceph/pull/5 running as a test, that should show this works for testing purposes.
@cloudnull we're working with RE to add a ceph job to maas, but that isn't in place yet, once it is we'll be able to confirm that, would prefer to get this merged sooner rather than later though.

**Comment by andymcc** [comment]
works according to the test PR

**Pull request merged**
