### PR TITLE
Add host and infra checks support for rpcr OSP13

### PR DESCRIPTION
**Pull request by tonytan4ever**

### CODE REVIEW

**Comment by tonytan4ever** [comment]
recheck_all

**Comment by hughsaunders** [comment]
recheck_all failures may have been caused by Jenkins outage RE-2210.

**Comment by tonytan4ever** [comment]
recheck_xenial_queens_deploy

**Comment by tonytan4ever** [comment]
recheck_xenial_queens_deploy

**Comment by tonytan4ever** [comment]
Good catch.  pacemaker.py added.

**Comment by tonytan4ever** [comment]
recheck_xenial_queens_deploy

**Comment by tonytan4ever** [comment]
recheck_xenial_queens_deploy

**Pull request merged**
