### PR TITLE
Add conntrack_count.py

### PR DESCRIPTION
**Pull request by git-harry**
This commit adds a plugin to allow the number of connections and the
maximum number allowed to be monitored.

Issue: https://github.com/rcbops/rpc-maas/issues/163

### CODE REVIEW

**Comment by stevelle** [comment]
:+1:

**Comment by claco** [comment]
-1 based on Darren's other comment here https://github.com/rcbops/rpc-extras/pull/49#issuecomment-89207780

Specifically, the original ask was for /proc/sys/net/ipv4/netfilter/ip_conntrack_count, not /proc/sys/net/netfilter/nf_conntrack_count, which seems to imply that the original request and the proposed solution are out of sync on intent somehow. Should clarify before moving forward.

**Comment by cemason** [comment]
Sorry for that - the request should be for nf_conntrack_count and _max rather than ip_conntrack_count and _max.

**Comment by nrb** [comment]
+1

**Comment by mancdaz** [comment]
-1

I'd suggest a mention in the readme of the fact that in order to consume this plugin, one needs to ensure the nf_conntrack_ipv4 module is loaded, otherwise /proc/sys/net/netfilter/nf_conntrack_* entries will not exist. It was not loaded on the trusty image I tested this plugin on.

**Comment by stevelle** [comment]
Fair point. I didn't test a stock system.

**Comment by mancdaz** [comment]
@git-harry pls could you add readme note as suggested

**Comment by git-harry** [comment]
@mancdaz - I've already added readme notes. What have I missed?

**Comment by mancdaz** [comment]
@git-harry apologies

:+1:

**Comment by mattt416** [comment]
Hi @git-harry, can you set file perms to 755?

**Comment by mattt416** [comment]
@git-harry In this case it's a bit trivial, but we should probably get into the habit of feeding back the cause of the failure to maas for issues that we expect or know may happen (in this case, kernel module not being loaded and therefore the files in question not being present).  Can you update it to do that?  I'm happy otherwise and will merge once that's in.  Thanks!

**Comment by git-harry** [comment]
@mattt416 - I'd considered the exception fairly self-explanatory and with the way maas_common works that automatically gets reported. However after our discussion I have added the additional error handling.

**Comment by mattt416** [comment]
LGTM

**Pull request merged**
