### PR TITLE
Add environment directives to playbooks

### PR DESCRIPTION
**Pull request by kacieh80**

### CODE REVIEW

**Comment by hmakkapati** [comment]
@kacieh80 Took the liberty to resolve merge conflicts here, hope it's okay :)

**Comment by npawelek** [comment]
recheck_trusty_liberty_deploy
recheck_xenial_pike_deploy
recheck_trusty_mitaka_deploy

**Comment by hmakkapati** [comment]
recheck_xenial_pike_deploy

**Comment by kacieh80** [comment]
recheck_trusty_liberty_deploy
recheck_xenial_pike_deploy
recheck_trusty_mitaka_deploy

**Comment by tonytan4ever** [comment]
Also can we add release note on this one?

The step to add release note:
install [reno](https://docs.openstack.org/reno/latest/user/index.html) first,
then
$ reno new <add-environment-directives>  # or similar name like that
Then edit the release note generated under releasenotes/notes to reflect the change you have made.

LMK if there is questions related to release notes.

**Comment by tonytan4ever** [comment]
recheck_all

**Pull request merged**
