### PR TITLE
Restructured the RPC-MAAS role

### PR DESCRIPTION
**Pull request by cloudnull**
This change restructures the rpc-maas tasks so that there's reduced
duplication and a lot more clarity regarding the tasks being executed.
The task files are all now prefixed with "maas_" and grouped based on
their various concerns.

This also brings with it the first set of dynamically generated checks
which is starting with the basic CDM checks. These checks have been
moved into the vars/main.yml file. This removes the template sprawl we
have and allows checks to be generated with a common core.

Signed-off-by: Kevin Carter <kevin.carter@rackspace.com>

### CODE REVIEW

**Comment by mkam** [comment]
recheck_cit_all

**Comment by cloudnull** [comment]
recheck_cit_all

**Comment by cloudnull** [comment]
@prometheanfire not likely to be able to split it into multiple reviews, the nature of this change is to pull the role forward using ansible best practices and logical task names. Shimming this change into the old structure for more incremental change won't be worth the effort.

**Comment by prometheanfire** [comment]
sure, but I don't have to be happy about it.

**Comment by cloudnull** [comment]
This is true! I appreciate your unhappy review.

**Comment by prometheanfire** [comment]
best type of review :D

**Comment by d34dh0r53** [comment]
Looks good to me!

**Pull request merged**
