### PR TITLE
Update maas to support recent version of OpenStack

### PR DESCRIPTION
**Pull request by cloudnull**
These changes allow maas to run with modern openstack APIs. This work
was done as part of the tools team deployment within an RPCO lab
environment where maas was deployed on the Rocky version of OpenStack on
ubuntu 18.04. While the deployment validation was done on Rocky the
changes will benifit the tooling as a whole allowing us to better serve
our existing customers.

Signed-off-by: Kevin Carter <kevin.carter@rackspace.com>

### CODE REVIEW

**Comment by npawelek** [comment]
Looks like some of these issues also affected queens builds. i.e. glance endpoint changes.

**Comment by npawelek** [comment]
recheck_all

**Comment by tonytan4ever** [comment]
recheck_all

**Comment by npawelek** [comment]
recheck_container_bashate_tox-test
recheck_container_pep8_tox-test
recheck_container_ansible-lint_tox-test

**Comment by npawelek** [comment]
recheck_bionic_rocky_deploy

**Comment by npawelek** [comment]
recheck_xenial_queens_deploy

**Comment by npawelek** [comment]
recheck_xenial_queens_deploy

**Comment by npawelek** [comment]
recheck_bionic_rocky_deploy

**Comment by npawelek** [comment]
recheck_xenial_rocky_deploy

**Comment by tonytan4ever** [comment]
recheck_bionic_mnaio_osp13_deploy

**Comment by tonytan4ever** [comment]
recheck_xenial_pike_deploy

**Comment by cloudnull** [comment]
recheck_bionic_mnaio_osp13_deploy

**Comment by tonytan4ever** [comment]
recheck_bionic_mnaio_osp13_deploy

**Comment by tonytan4ever** [comment]
recheck_xenial_pike_deploy 
recheck_xenial_rocky_deploy
recheck_bionic_mnaio_osp13_deploy

**Comment by tonytan4ever** [comment]
recheck_xenial_queens_deploy

**Comment by tonytan4ever** [comment]
recheck_bionic_mnaio_osp13_deploy

**Comment by tonytan4ever** [comment]
recheck_bionic_mnaio_osp13_deploy

**Comment by tonytan4ever** [comment]
recheck_ bionic_mnaio_osp13_deploy

**Comment by tonytan4ever** [comment]
recheck_bionic_mnaio_osp13_deploy

**Comment by tonytan4ever** [comment]
recheck_bionic_mnaio_osp13_deploy

**Pull request merged**
