### PR TITLE
TURTLES-313 add ssl support to keystone_api_local_check

### PR DESCRIPTION
**Pull request by michaelrice**
* Adding protocol and port option to local keystone api check.
* Renamed local variable in function to be all lower case per pep8 standards.

Signed-off-by: Michael Rice <michael@michaelrice.org>

### CODE REVIEW

**Comment by tonytan4ever** [comment]
Seems like there is an issue with this change:

> {"attempts": 15, "changed": false, "cmd": ["/openstack/venvs/maas-0.0.0/bin/python", "/opt/rpc-maas-tools/rpc-maas-tool.py", "--logfile", "/var/lib/jenkins/workspace/PR_rpc-maas-master-xenial-pike-deploy/artifacts/rpc-maas-logs.txt", "verify-local"], "delta": "0:00:18.546618", "end": "2018-03-19 23:50:02.491275", "failed": true, "rc": 1, "start": "2018-03-19 23:49:43.944657", "stderr": "", "stderr_lines": [], "stdout": "The following metrics are required by alarms but not produced by any checks: set(['keystone_api_local_status'])\nThe following checks failed to execute or didn't return 'okay' as their status: [('keystone_api_local_check--aio1_keystone_container-cc6e7165', \"/openstack/venvs/maas-0.0.0/local/lib/python2.7/site-packages/keystoneauth1/adapter.py:179: UserWarning: Using keystoneclient sessions has been deprecated. Please update your software to use keystoneauth1.\\n  warnings.warn('Using keystoneclient sessions has been deprecated. '\\nstatus error Unable to establish connection to http://172.29.239.189:3535735357/v3/services\\n\")]", "stdout_lines": ["The following metrics are required by alarms but not produced by any checks: set(['keystone_api_local_status'])", "The following checks failed to execute or didn't return 'okay' as their status: [('keystone_api_local_check--aio1_keystone_container-cc6e7165', \"/openstack/venvs/maas-0.0.0/local/lib/python2.7/site-packages/keystoneauth1/adapter.py:179: UserWarning: Using keystoneclient sessions has been deprecated. Please update your software to use keystoneauth1.\\n  warnings.warn('Using keystoneclient sessions has been deprecated. '\\nstatus error Unable to establish connection to http://172.29.239.189:3535735357/v3/services\\n\")]"]}

**Comment by michaelrice** [comment]
How? It takes something that is hard coded makes it a parameter, and uses what was hard coded as the default..

**Comment by michaelrice** [comment]
Oh I see it

**Comment by michaelrice** [comment]
fixed.

**Pull request merged**
