### PR TITLE
For RPC-R: Add default ansible user and become 

### PR DESCRIPTION
**Pull request by tonytan4ever**
tasks with "delegate_to: "{{ physical_host | default(ansible_host) }}"
need to have ansible user set and become: yes

### CODE REVIEW

**Comment by tonytan4ever** [comment]
trusty_mitaka_deploy

**Comment by tonytan4ever** [comment]
recheck_trusty_mitaka_deploy

**Comment by tonytan4ever** [comment]
recheck_all

**Comment by kacieh80** [comment]
@tonytan4ever There are many places in the code you might need to make this change: https://github.com/rcbops/rpc-maas/search?q=delegate_to&unscoped_q=delegate_to

**Comment by tonytan4ever** [comment]
> @tonytan4ever There are many places in the code you might need to make this change: https://github.com/rcbops/rpc-maas/search?q=delegate_to&unscoped_q=delegate_to

@kacieh80 :  yes,  that's where I need help with adding those lines.

**Comment by kacieh80** [comment]
> > @tonytan4ever There are many places in the code you might need to make this change: https://github.com/rcbops/rpc-maas/search?q=delegate_to&unscoped_q=delegate_to
> 
> @kacieh80 : yes, that's where I need help with adding those lines.

Ah ok, I'll update this soon

**Comment by kacieh80** [comment]
@cloudnull @npawelek this is ready for review

**Comment by kacieh80** [comment]
recheck_container_bashate_tox

**Pull request merged**
