### PR TITLE
Add hp_monitoring.py script

### PR DESCRIPTION
**Pull request by git-harry**
The hp_monitoring.py script adds basic hardware monitoring for HP boxes
and is designed to complement the openmanage.py script for Dell
hardware.

The script makes use of the utilities hpasmcli and hpssacli. Details of
the repo from which to get them can be found at
https://downloads.linux.hp.com/SDR/project/mcp/. The packages installed
were hp-health and hpssacli.

### CODE REVIEW

**Comment by claco** [comment]
Should we add the installation of those packages to an hp.yml and hp_steup.yml in rpc-extras like we did for Dell?  https://github.com/rcbops/rpc-extras/tree/master/playbooks/roles/rpc_maas/tasks

**Comment by git-harry** [comment]
@claco - I don't believe rpc-extras installs any apt packages.

**Comment by mancdaz** [comment]
@git-harry as per the dell plugin:

https://github.com/rcbops/rpc-maas/blob/master/openmanage.py#L23

...perhaps we want a version check in here in case the output format changes between versions.  Especially given the very specific nature of some of the strings being matched - I'm looking at you 'OK)':

https://github.com/rcbops/rpc-maas/pull/187/files#diff-638695592750f3188a3ec56b99bf2cd9R38

**Comment by mancdaz** [comment]
Also please add the Apache license found at the top of (most of) the other plugins (we can fix the others separately)

**Comment by git-harry** [comment]
@mancdaz - I didn't add any version checking because I couldn't find a way to get a version out of hpasmcli

**Comment by andymcc** [comment]
tested the hp_monitoring script, works fine - @mancdaz are we good to merge it - will require a rebase though.

**Comment by mancdaz** [comment]
@andymcc yes - once rebased I'm happy for this to get merged.

**Comment by git-harry** [comment]
@andymcc - done

**Pull request merged**
