### PR TITLE
Conntrack icehouse

### PR DESCRIPTION
**Pull request by hughsaunders**
This commit adds a plugin to allow the number of connections and the
maximum number allowed to be monitored.

Issue: #163
(cherry picked from commit 7724f30)
(cherry picked from commit ce6c10e)
(cherry picked from commit a0865f1)
(cherry picked from commit d62594b)
(cherry picked from commit b317187)
(cherry picked from commit 9bdf813)

### CODE REVIEW

**Comment by git-harry** [comment]
-1 - Increase control on data printed is going to break things

**Comment by sigmavirus24** [comment]
Yeah I think we should just be backporting (and perhaps, partially-updating) the conntrack stuff instead of backporting the work to buffer the printing of output.

**Comment by git-harry** [comment]
@sigmavirus24 - agreed.

**Comment by git-harry** [comment]
Replaced by https://github.com/rcbops/rpc-maas/pull/199

**Pull request closed without merging**
