### PR TITLE
Add local and remote Ironic API monitoring

### PR DESCRIPTION
**Pull request by cfarquhar**
This commit adds local and remote Ironic API monitoring to Rackspace MaaS.

### CODE REVIEW

**Comment by cloudnull** [comment]
recheck_cit_trusty_newton

**Comment by cloudnull** [comment]
recheck_cit_trusty_xenial

**Comment by cloudnull** [comment]
recheck_cit_xenial_newton

**Comment by cloudnull** [comment]
We need to get a couple changes in to make the linter happy otherwise LGTM.

**Comment by cfarquhar** [comment]
rebased and fixed pep8 issues

**Pull request merged**
