### PR TITLE
Ironic Maas support 

### PR DESCRIPTION
**Pull request by tonytan4ever**

### CODE REVIEW

**Comment by tonytan4ever** [comment]
@cloudnull @mancdaz:
These commits have their commit messages as release notes, let me know if that's cool with you guys.
https://github.com/rcbops/rpc-maas/pull/334/commits/dfa20091d401985e6ba3953056cce2ee3d7fe8b5
https://github.com/rcbops/rpc-maas/pull/334/commits/5c73390f69223e275e5002a9e6e5e454ee33f137
and https://github.com/rcbops/rpc-maas/pull/334/commits/70e1bde2aa701b68c0a4782857933d97bfd9e714

**Comment by mancdaz** [comment]
Hi @tonytan4ever, there is a tool called reno which we use to track release notes. When it comes to releasing anything from any of the repos we track, we are able to auto-generate release notes using what has been written with reno. See https://github.com/rcbops/rpc-maas/pull/288 for an example, and docs on [reno](http://rackerlabs.github.io/docs-rackspace/tools/reno-notes.html).

A release note should be included with each commit where significant change or new feature has been introduced.

Thanks!

**Comment by cloudnull** [comment]
recheck_cit_all

**Comment by cloudnull** [comment]
recheck_cit_trusty_newton

**Comment by tonytan4ever** [comment]
@mancdaz:  I have added in release notes in the latest commit.  Let me know if there is any other issues. 
Thank you.

**Comment by cloudnull** [comment]
recheck_cit_all

**Comment by cloudnull** [comment]
recheck_cit_trusty_newton
recheck_cit_trusty_liberty

**Comment by cloudnull** [comment]
recheck_cit_trusty_newton

**Pull request merged**
