### PR TITLE
Modify MaaS testing to support snapshot builds

### PR DESCRIPTION
**Pull request by xeregin**

### CODE REVIEW

**Comment by npawelek** [comment]
recheck_bionic_mnaio_osp13_deploy

**Comment by xeregin** [comment]
recheck_unit_tests

**Comment by odyssey4me** [comment]
FYI the term `snapshot` refers to AIO snapshots, whereas the MNAIO tooling refers to `images`. It may be good to use the appropriate terminology for the job names and scripts to prevent confusion.

**Comment by cloudnull** [comment]
abandoned

**Pull request closed without merging**
