### PR TITLE
TURTLES-313

### PR DESCRIPTION
**Pull request by michaelrice**
Added port and protocol to all the remaining plugins to address #TURTLES-313

### CODE REVIEW

**Comment by michaelrice** [comment]
I wasnt sure if yall would want this as 1 commit per plugin I edited or if I should rebase this all into 1 single commit, just let me know if you want me to rebase it.

**Comment by tonytan4ever** [comment]
recheck_cit_trusty_liberty_deploy
recheck_cit_trusty_mitaka_deploy
recheck_cit_trusty_newton_deploy
recheck_cit_xenial_newton_deploy
recheck_cit_xenial_pike_deploy

**Comment by tonytan4ever** [comment]
Multiple commits are fine.

This is the error we are getting, trying to figure out why:

TASK: [Run MaaS verify local] ************************************************* 
fatal: [aio1] => SSH Error: mux_client_hello_exchange: write packet: Broken pipe
It is sometimes useful to re-run the command using -vvvv, which prints SSH debug output to help diagnose the issue.

**Comment by michaelrice** [comment]
@tonytan4ever good catch. I fixed it.

**Pull request closed without merging**
