### PR TITLE
Detect container hosts

### PR DESCRIPTION
**Pull request by cloudnull**
Added step to detect and limit container storage checks to only contianer
hosts. This ensures we're not attempting to deploy container checks on
non-container hosts.

Signed-off-by: Kevin Carter <kevin.carter@rackspace.com>

### CODE REVIEW

**Comment by evrardjp** [comment]
Weirdly github doesn't allow me to review the typo you did on the first commit message. Or I can't use it properly I don't know.

**Comment by cloudnull** [comment]
@npawelek @evrardjp I squashed these last two commits. please review when you have a chance.

**Comment by cloudnull** [comment]
recheck_cit_all

**Comment by cloudnull** [comment]
last failure was due to timeout on getting a worker... "Cancelling nested steps due to timeout"

**Pull request merged**
